config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'welcome/index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :packages do
    resources :comments
  end

  resources :users do
    resources :have_lists
    resources :wants_lists
  end

  resources :have_lists do
    resources :packages
  end

  resources :wants_lists do
    resources :packages
  end

  root 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :wants_list, dependent: :destroy
  has_one :have_list, dependent: :destroy
  validates :name, presence: true
  EMAIL_FORMAT_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: EMAIL_FORMAT_REGEX }, uniqueness: true

  before_save { self.email = email.downcase }

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if !current_user.nil?
      @users = User.all
    else
      redirect_to root_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show

    if @user == current_user || current_user.admin
      @user = User.find(params[:id])
      @have_list = @user.have_list
    else
      redirect_to login_path
    end
    @users = User.all
  end


  def check_match
    CheckMatch.new().check_match(current_user, @users)
  end
  helper_method :check_match

  # GET /users/new
  def new
    @user = User.new
    @package = Package.all
    @have_list = HaveList.all
  end

  # GET /users/1/edit
  def edit
  #  render plain: params.inspect
    if @user == current_user || current_user.admin
      @user = User.find(params[:id])
      @package = Package.all
      @have_list = HaveList.all
    else
      redirect_to login_path
    end

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save

      login(@user)

    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json

  def destroy

    if @user == current_user || current_user.admin
    @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: '' }
        format.json { head :no_content }
      end
    else
      redirect_to login_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :password, :password_confirmation, :active, :package_ids => [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <div class="col-xs-12 col-md-7 col-xl-5">
    <div class="bg-dark user-wrapper">
      <div class="m-3" align="left">
        <%= form_with model: @user, local: true do |f| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h4><%= pluralize(user.errors.count, "error") %> förhindrade att konto kunde skapas:</h4>

              <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <p>
              <%= f.label :smeknamn, :for => 'name' %><br>
              <%= f.text_field :name, :class => 'form-control', :id =>'name' %>
            </p>
            <p>
              <%= f.label :epost, :for => 'email' %><br>
              <%= f.email_field :email, :class => 'form-control', :id => 'email' %>
            </p>
            <p>
              <%= f.label :lösenord, :for => 'pasword' %><br>
              <%= f.password_field :password, :class => 'form-control', :id => 'password' %>
            </p>
            <p>
              <%= f.label :bekräfta_lösenord, :for => 'pasword_confirmation' %><br>
              <%= f.password_field :password_confirmation, :class => 'form-control', :id => 'password_confirmation' %>
            </p>
              <p>
              <%= f.submit "Skapa konto",  :class => 'btn btn-primary btn-block mt-4' %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/_form_edit.html.erb
  <div class="col-xs-12 col-md-7 col-xl-5">
    <div class="bg-dark user-wrapper" align="left">
      <div class="m-3">
        <%= form_with model: @user, local: true do |f| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> förhindrade att konto kunde skapas:</h2>

              <ul>
              <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <p>
              <%= f.label :smeknamn, :for => 'name' %><br>
              <%= f.text_field :name, :class => 'form-control', :id =>'name' %>
            </p>
            <p>
              <%= f.label :epost, :for => 'email' %><br>
              <%= f.email_field :email, :class => 'form-control', :id => 'email' %>
            </p>
            <p>
              <%= f.label :lösenord, :for => 'pasword' %><br>
              <%= f.password_field :password, :class => 'form-control', :id => 'password' %>
            </p>
            <p>
              <%= f.label :bekräfta_lösenord, :for => 'pasword_confirmation' %><br>
              <%= f.password_field :password_confirmation, :class => 'form-control', :id => 'password_confirmation' %>
            </p>
              <% if current_user.admin %>
              <p>
                <%= f.label :active, :for =>'active' %>&nbsp;
                <%= f.check_box :active, :class => 'form-control', :id => 'active' %>
              </p>
              <% end %>
              <p>
              <%= f.submit "Spara",  :class => 'btn btn-primary btn-block mt-4' %>
            </p>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<div class="mt-5" align="center">
<h1>Dina uppgifter</h1>

<%= render 'form_edit', user: @user %>

<div class="m-3">
<%= link_to 'Tillbaka', @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vänner</h1>

<div class="row mt-3" align="left">

  <% @users.each do |user| %>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
      <% if user == current_user %>
      <div class="bg-dark mt-3 current-user-wrapper">
      <% else %>
      <div class="bg-dark mt-3 user-wrapper">
      <% end %>
        <div class="card-body">
          <h4 class="card-title">
            <% if user == current_user %>
              Du
            <% else %>
              <%= user.name %>
            <% end %>
          </h4>
          <div class="card-text list-item">
            <% if user.have_list.nil? || user.have_list.packages.nil? %>
              <div class="small-text dark-text">(saknar lista)</div><br><br>
            <% else %>
              Har listat följande:<br><span>
              <% user.have_list.packages.each do |p| %>
                <% if !current_user.have_list.nil? %>
                  <% current_user.have_list.packages.each do |c| %>
                    <% if p == c && current_user != user %>
                      </span><span class="match-text">
                    <% end %>
                    <% end %>
                <% end %>
                <div class="mt-1"><%= image_tag(p.logo, :alt => p.provider, :width => "20", :class => "mr-2") %><%= p.provider %> | <%= p.name %></span><br>
                </div>
              <% end %>
            <% end %>
          </div>
          <p class="card-text mt-2">
            <% if user == current_user %>
              <%= link_to 'Uppdatera', user_path(user), :class => 'btn btn-secondary btn-sm small-text' %>
            <% elsif current_user.admin %>
              <%= link_to 'Ändra', edit_user_path(user), :class => 'btn btn-warning btn-sm small-text' %>
              <%= link_to 'Radera', user, method: :delete, data: { confirm: 'Är du säker?' }, :class => 'btn btn-danger btn-sm small-text' %>
            <% else %>
              &nbsp;
            <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="row justify-content-center">
  <div class="col-xs-6 col-sm-6 col-md-3 col-lg-2 col-xl-2">
  <%= link_to 'Tillbaka', user_path(current_user), :class =>'btn btn-outline-primary btn-block btn-sm mt-3' %>
  </div>
  <div class="col-xs-6 col-sm-6 col-md-3 col-lg-2 col-xl-2">
  <%= link_to 'Logga ut', logout_path, method: :delete, :class =>'btn btn-outline-primary btn-block btn-sm mt-3' %>
  </div>
</div>
<div class="mt-2 mb-3 small-text dark-text" align="center">
  &copy; Maxkungen 2020
</div>

app/views/users/index_backup.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Email</th>
      <th>Have List</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td>
          <% if user.have_list.nil? || user.have_list.packages.nil? %>
            3
          <% else %>
            <% user.have_list.packages.each do |p| %>
              <%= p.name %><br>
            <% end %>
          <% end %>

        <% if user == current_user || current_user.admin %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% else %>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div align="center" class="mt-5">
  <h1>Skapa ett konto</h1>

  <%= render 'form', user: @user %>

  <div class="body-text m-4">
    Har du redan ett konto? <%= link_to 'Logga in', login_path %>
  </div>

</div>

app/views/users/show.html.erb
<div class="mt-3 mb-3" align="center">

  <%= image_tag("delastream.png", :alt => "De La Stream", :width => "260", :class => "mb-2") %><br>
<p id="notice"><%= notice %></p>

<div class="col-xs-12 col-md-8 col-xl-6">
  <div class="bg-dark user-wrapper" align="left">
    <div class="m-3">

      <h3>Hej <%= current_user.name %>!</h3>

      <p class="body-text">
        Här kan du skapa en lista över de streamingtjänster som du önskar att dela med någon vän. Du kanske redan har ett paket idag som du kan dela eller så önskar du att skaffa ett paket men vill ha med dig någon. Skapa en lista över dessa så matchas du ihop med andra som är ute efter samma paket.
      </p>

      <div class="mt-5">
        <h5>Dina streamingpaket</h5>
        <p class="small-text">
          <% if !@user.have_list %>
          Du har ingen lista över streamingtjänster än.<br>
            <%= link_to 'Skapa lista', new_have_list_path(@user.id), :class => 'btn btn-success mt-2' %>
          <% else %>
          Här kan du lägga till och ta bort stremingtjänster från din lista.<br>
            <%= link_to 'Uppdatera din lista', edit_have_list_path(@user.id), :class => 'btn btn-secondary mt-2' %>
            <% end %>
        </p>
      </div>
      </div>
    </div>


    <div class="bg-dark user-wrapper mt-3" align="left">
      <div class="m-3">

        <% if !current_user.have_list.nil? || !current_user.wants_list.nil? %>
        <div class="mt-2 mb-4">
          <h3>Vänner</h3>
          <% if check_match.length == 0 %>
            <p class="small-text">
              Inga vänner är för närvarande ute efter samma tjänster som dig.
            </p>
          <% else %>
          <p class="small-text">
            Följande vänner är också ute efter något av streamingpaket du listat:
          </p>
          <p class="body-text"><b>
            <% check_match.each do | user | %>
              <%= user.name %><br>
            <% end %></b>
          </p>
          <% end %>
        </div>
        <% end %>
        <div class="mb-3">

          <%= link_to 'Visa alla vänner', users_path, :class => 'btn btn-primary btn-block' %>
        </div>
        </div>
      </div>





    <div class="bg-dark user-wrapper mt-3" align="left">
      <div class="m-3">


        <div class="mt-2 mb-4">
          <h3>Dina uppgifter</h3>

          <p class="body-text">
            <strong>Name:</strong>
            <%= @user.name %>
            <br>
            <strong>Email:</strong>
            <%= @user.email %>
            <br>
            <%= link_to 'Ändra dina uppgifter', edit_user_path(@user) %> |
            <%= link_to 'Radera ditt konto', @user, method: :delete, data: { confirm: 'Är du säker?' } %>
          </p>
        </div>

        <%= link_to 'Logga ut', logout_path, method: :delete, :class =>'btn btn-outline-primary btn-block' %>

        </div>
      </div>
      <div class="mt-2 mb-3 small-text dark-text" align="center">
        &copy; Maxkungen 2020
      </div>
      </div>
    </div>